export const se = [
	{
		"yr": "1962",
		"Skellefteå AIK": 3,
		"Åtvidabergs FF": 3,
		"Östers IF": 4,
		"IK Oddevold": 4,
		"GIF Sundsvall": 4,
		"IK Brage": 4,
		"IFK Eskilstuna": 5,
		"Redbergslids IK (U)": 5,
		"IFK Luleå": 5,
		"BK Derby": 5,
		"Saltö BK (U)": 6,
		"Söderhamns IF (U)": 6,
		"IFK Stockholm": 6,
		"Halmstads BK": 6,
		"SK Sifhälla": 7,
		"Sandvikens AIK (U)": 7,
		"Malmö BI": 7,
		"Gimonäs CK (U)": 7,
		"Avesta AIK": 8,
		"Jönköpings Södra": 8,
		"Bodens BK": 8,
		"Motala AIF": 8,
		"Kalmar FF": 9,
		"Varbergs BoIS (U)": 9,
		"IFK Kalix": 9,
		"IFK Kumla (U)": 9,
		"Karlstads BIK": 10,
		"Råå IF": 10,
		"Tidaholms GIF (U)": 10,
		"Skellefteå IF (U)": 10,
		"IK Sleipner (U)": 11,
		"Billingsfors IK": 11,
		"IK Sirius (U)": 11,
		"Köpings IS": 12,
		"Tomelilla IF (U)": 12,
		"Kungshamns IF": 12
	},
	{
		"yr": "1963",
		"IFK Eskilstuna": 1,
		"Östers IF": 1,
		"GIF Sundsvall": 1,
		"Gais": 1,
		"Åtvidabergs FF": 2,
		"Sandvikens IF": 2,
		"IFK Holmsund": 2,
		"IFK Malmö (N)": 2,
		"Redbergslids IK": 3,
		"IK Brage": 3,
		"IF Saab (U)": 3,
		"Skellefteå AIK": 3,
		"BK Derby": 4,
		"Norrby IF": 4,
		"Sundbybergs IK": 4,
		"IFK Luleå": 4,
		"Lycksele IF": 5,
		"Högadals IS (N)": 5,
		"IFK Stockholm": 5,
		"Landskrona BoIS": 5,
		"IFK Kristianstad": 6,
		"Varbergs BoIS": 6,
		"Sandåkerns SK (U)": 6,
		"Sandvikens AIK": 6,
		"Malmö BI": 7,
		"Hallstahammars SK (U)": 7,
		"Husqvarna IF (U)": 7,
		"Söderhamns IF": 7,
		"IFK Sunne": 8,
		"Kalmar FF": 8,
		"Gunnarstorps IF (U)": 8,
		"Gimonäs CK": 8,
		"Halmstads BK": 9,
		"Bromölla IF (U)": 9,
		"Bollnäs GIF (U)": 9,
		"SK Sifhälla (U)": 9,
		"Jönköpings Södra": 10,
		"Avesta AIK": 10,
		"Norsjö IF (U)": 10,
		"Västra Frölunda (U)": 10,
		"Motala AIF": 11,
		"IK Oddevold": 11,
		"IK City (U)": 11,
		"IFK Kumla": 12,
		"Kinna IF (U)": 12,
		"Saltö BK": 12
	},
	{
		"yr": "1964",
		"GIF Sundsvall": 1,
		"Halmstad BK": 1,
		"Hammarby IF": 1,
		"Östers IF": 1,
		"Hammarby IF": 1,
		"Gunnarstorps IF": 2,
		"Åtvidabergs FF": 2,
		"IFK Holmsund": 2,
		"Sundbybergs IK": 2,
		"GIF Sundsvall": 2,
		"Skellefteå AIK": 3,
		"IK Brage": 3,
		"Östers IF": 3,
		"Grimsås IF (U)": 3,
		"IFK Kristianstad": 3,
		"Gefle IF (U)": 4,
		"Landskrona BoIS": 4,
		"Halmstads BK": 4,
		"Råsunda IS (U)": 4,
		"Högadals IS": 4,
		"IS Halmia (N)": 5,
		"IFK Stockholm": 5,
		"IFK Ystad (U)": 5,
		"Lycksele IF": 5,
		"Sandvikens IF": 6,
		"IFK Östersund (U)": 6,
		"Gnösjö IF (U)": 6,
		"IF Saab": 6,
		"SK Sifhälla": 7,
		"Sandåkerns SK": 7,
		"IFK Malmö": 7,
		"Kalmar FF": 7,
		"Luleå SK (U)": 8,
		"Bromölla IF": 8,
		"Redbergslids IK": 8,
		"Sandvikens AIK": 8,
		"IFK Karlshamn (U)": 9,
		"Karlstad BK (U)": 9,
		"Söderhamns IF": 9,
		"Varbergs BoIS": 9,
		"BK Derby": 10,
		"IFK Luleå": 10,
		"Norrby IF": 10,
		"Västerås IK (U)": 10,
		"Husqvarna IF": 11,
		"Malmö BI": 11,
		"IFK Sunne": 11,
		"Nyköpings AIK (U)": 12,
		"Hallstahammars SK": 12,
		"Billingsfors IK (U)": 12
	},
	{
		"yr": "1965",
		"Gais": 1,
		"IK Brage": 1,
		"Grimsås IF": 1,
		"Gefle IF": 1,
		"Gais (N)": 1,
		"IFK Stockholm": 2,
		"Sandvikens AIK": 2,
		"Östers IF": 2,
		"IK Brage": 2,
		"Landskrona BoIS": 2,
		"IFK Holmsund": 3,
		"IFK Eskilstuna (N)": 3,
		"GIF Nike (U)": 3,
		"Hässleholms IF (U)": 3,
		"Grimsås IF": 3,
		"Gunnarstorps IF": 4,
		"SK Sifhälla": 4,
		"Gefle IF": 4,
		"Lycksele IF": 4,
		"IF Saab": 4,
		"Bromölla IF": 5,
		"Sundbybergs IK": 5,
		"IFK Östersund": 5,
		"IFK Malmö": 5,
		"Kalmar FF": 6,
		"Luleå SK": 6,
		"Karlstad BK": 6,
		"IS Halmia": 6,
		"IFK Ystad": 7,
		"Sandvikens IF": 7,
		"Brynäs IF (U)": 7,
		"Jönköpings Södra (U)": 7,
		"Västerås SK (U)": 8,
		"Sandåkerns SK": 8,
		"Åtvidabergs FF": 8,
		"Redbergslids IK": 8,
		"Gnosjö IF": 9,
		"Skellefteå AIK": 9,
		"Södertälje SK (U)": 9,
		"Varbergs BoIS": 9,
		"Halmstads BK": 10,
		"IFK Kristianstad": 10,
		"Sunnanå SK (U)": 10,
		"Råsunda IS": 10,
		"Västra Frölunda (U)": 11,
		"Högadals IS": 11,
		"IF Karlskoga-Bofors (U)": 11,
		"IFK Karlshamn": 12,
		"Göteborgs AIK (U)": 12,
		"IF Sylvia (U)": 12
	},
	{
		"yr": "1966",
		"IFK Holmsund": 1,
		"Hammarby IF": 1,
		"IF Saab": 1,
		"Gunnarstorps IF": 1,
		"Hammarby IF (N)": 1,
		"IFK Stockholm": 2,
		"Åtvidabergs FF": 2,
		"IFK Malmö": 2,
		"IFK Holmsund": 2,
		"Sandvikens AIK": 2,
		"Jönköping Södra": 3,
		"IFK Eskilstuna": 3,
		"Gunnarstorps IF": 3,
		"Landskrona BoIS": 3,
		"GIF Sundsvall (N)": 3,
		"Brynäs IF": 4,
		"Östers IF": 4,
		"Sundbybergs IK": 4,
		"IF Saab": 4,
		"Grimsås IF": 4,
		"Alingsås IF (U)": 5,
		"Bromölla IF": 5,
		"IFK Luleå (U)": 5,
		"Västerås SK": 5,
		"Sandåkerns SK": 6,
		"Sandvikens IF": 6,
		"IS Halmia": 6,
		"Redbergslids IK": 6,
		"Hässleholms IF": 7,
		"Luleå SK": 7,
		"Södertälje SK": 7,
		"Skogens IF (U)": 7,
		"Karlstad BK": 8,
		"Kalmar FF": 8,
		"Gnosjö IF": 8,
		"Domsjö IF (U)": 8,
		"Lycksele IF": 9,
		"Avesta AIK (U)": 9,
		"Finspångs AIK (U)": 9,
		"IFK Ystad": 9,
		"Gefle IF": 10,
		"Mönsterås GIF (U)": 10,
		"Tidaholms GIF (U)": 10,
		"IFK Östersund": 10,
		"Malmö BI (U)": 11,
		"Gimo IF (U)": 11,
		"Varbergs BoIS": 11,
		"IFK Sunne (U)": 12,
		"SK Sifhälla": 12,
		"GIF Nike": 12
	},
	{
		"yr": "1967",
		"Åtvidabergs FF": 1,
		"Östers IF": 1,
		"Åtvidabergs FF": 1,
		"IK Brage (N)": 1,
		"Sandvikens IF": 1,
		"Degerfors IF (N)": 2,
		"Östers IF": 2,
		"Ifö/Bromölla IF": 2,
		"GIF Sundsvall": 2,
		"Västra Frölunda (U)": 2,
		"IFK Eskilstuna": 3,
		"Skövde AIK (U)": 3,
		"IK Brage": 3,
		"Brynäs IF": 3,
		"IS Halmia": 3,
		"IF Friska Viljor (U)": 4,
		"IFK Malmö": 4,
		"Alingsås IF": 4,
		"Sandvikens IF": 4,
		"IK Sirius (U)": 4,
		"Sundbybergs IK": 5,
		"IFK Luleå": 5,
		"Kalmar FF": 5,
		"Grimsås IF": 5,
		"IF Saab": 6,
		"IFK Trelleborg (U)": 6,
		"Sandåkerns SK": 6,
		"Västerås SK": 6,
		"BK Derby (U)": 7,
		"Landskrona BoIS": 7,
		"Skellefteå AIK/IF (U)": 7,
		"IFK Arvika (U)": 7,
		"Jönköping Södra": 8,
		"IFK Stockholm": 8,
		"Sölvesborgs GIF (U)": 8,
		"Domsjö IF": 8,
		"Sandvikens AIK": 9,
		"Skogens IF": 9,
		"Karlstad BK": 9,
		"Gnosjö IF": 9,
		"IFK Kristianstad (U)": 10,
		"Hallstahammars SK (U)": 10,
		"Luleå SK": 10,
		"Finspångs AIK": 10,
		"Gunnarstorps IF": 11,
		"Södertälje SK": 11,
		"Göteborgs AIK (U)": 11,
		"Redbergslids IK": 12,
		"Hässleholms IF": 12,
		"Avesta AIK": 12,
		"IFK Ystad": 13
	},
	{
		"yr": "1968",
		"Jönköping Södra": 1,
		"Jönköping Södra": 1,
		"IK Sirius": 1,
		"Sandvikens IF": 1,
		"Landskrona BoIS": 1,
		"Hammarby IF (N)": 2,
		"IK Sirius": 2,
		"Sandåkerns SK": 2,
		"Skövde AIK": 2,
		"IFK Trelleborg": 2,
		"Degerfors IF": 3,
		"Skogens IF": 3,
		"Ljusdals IF (U)": 3,
		"Sandvikens IF": 3,
		"Ifö/Bromölla IF": 3,
		"Kalmar FF": 4,
		"IFK Eskilstuna": 4,
		"IF Saab": 4,
		"Landskrona BoIS": 4,
		"IFK Luleå": 4,
		"IFK Holmsund (N)": 5,
		"IK Sleipner (U)": 5,
		"Grimsås IF": 5,
		"IK Brage": 5,
		"Skellefteå AIK/IF": 6,
		"Brynäs IF": 6,
		"Sölvesborgs GIF": 6,
		"Västra Frölunda": 6,
		"Karlstad BK": 7,
		"IFK Malmö": 7,
		"Sundbybergs IK": 7,
		"Gimonäs CK (U)": 7,
		"Råsunda IS (U)": 8,
		"Tidahholms GIF (U)": 8,
		"IS Halmia": 8,
		"Domsjö IF": 8,
		"IFK Värnamo (U)": 9,
		"IFK Stockholm": 9,
		"GIF Sundsvall": 9,
		"IFK Arvika": 9,
		"Nybro IF (U)": 10,
		"IF Friska Viljor": 10,
		"Norrby IF (U)": 10,
		"IF Karlskoga/Bofors (U)": 10,
		"Bodens BK (U)": 11,
		"Västerås SK": 11,
		"Gnosjö IF": 11,
		"Alingsås IF": 11,
		"Åshammars IK (U)": 12,
		"Frösö IF (U)": 12,
		"BK Derby": 12,
		"Åstorps IF (U)": 12
	},
	{
		"yr": "1969",
		"Hammarby IF": 1,
		"Örgryte IS (N)": 1,
		"Hälsingborgs IF (N)": 1,
		"Sandåkerns SK": 1,
		"Skövde AIK": 2,
		"Brynäs IF": 2,
		"Degerfors IF": 2,
		"IFK Malmö": 2,
		"IFK Eskilstuna": 3,
		"IF Saab": 3,
		"Kalmar FF": 3,
		"Domsjö IF": 3,
		"Halmstads BK (U)": 4,
		"IK Brage": 4,
		"IFK Holmsund": 4,
		"Västra Frölunda": 4,
		"IK Sleipner": 5,
		"GIF Sundsvall": 5,
		"IS Halmia": 5,
		"Sandvikens IF": 5,
		"IFK Trelleborg": 6,
		"IFK Stockholm": 6,
		"IFK Luleå": 6,
		"Tidaholms GIF": 6,
		"Landskrona BoIS": 7,
		"Malungs IF (U)": 7,
		"Ljusdals IF": 7,
		"Grimsås IF": 7,
		"IFK Arvika": 8,
		"Älvsjö AIK (U)": 8,
		"Hässleholms IF (U)": 8,
		"IFK Härnösand (U)": 8,
		"Södertälje SK (U)": 9,
		"Ifö/Bromölla IF": 9,
		"Skellefteå AIK": 9,
		"IFK Värnamo": 9,
		"Gimonäs CK": 10,
		"IK Atleten (U)": 10,
		"Skogens IF": 10,
		"Sundbybergs IK": 10,
		"Karlstad BK": 11,
		"Blomstermåla IK (U)": 11,
		"Råsunda IS": 11,
		"Gefle IF (U)": 11,
		"Kinna IF (U)": 12,
		"IFK Västerås (U)": 12,
		"Sölvesborgs GIF": 12,
		"Gällivare SK (U)": 12
	},
	{
		"yr": "1970",
		"Landskrona BoIS": 1,
		"Sandvikens IF": 1,
		"Skövde AIK": 1,
		"IFK Luleå": 1,
		"Landskrona BoIS": 1,
		"Sandåkerns SK": 2,
		"IK Sirius (N)": 2,
		"IFK Luleå": 2,
		"KB Karlskoga (U)": 2,
		"Hälsingborgs IF": 2,
		"Sandvikens IF": 3,
		"Nybro IF (U)": 3,
		"IK Brage": 3,
		"IF Saab": 3,
		"GIF Sundsvall": 3,
		"Skövde AIK": 4,
		"IFK Stockholm": 4,
		"IFK Malmö": 4,
		"Jönköpings Södra (N)": 4,
		"IFK Holmsund": 4,
		"IFK Eskilstuna": 5,
		"Perstorps SK (U)": 5,
		"Västra Frölunda": 5,
		"Brynäs IF": 5,
		"Skellefteå AIK": 6,
		"Grimsås IF": 6,
		"IK Sleipner": 6,
		"Halmstads BK": 6,
		"Degerfors IF": 7,
		"Domsjö IF": 7,
		"IF Brommapojkarna (U)": 7,
		"Kalmar FF": 7,
		"Älvsjö AIK": 8,
		"IFK Trelleborg": 8,
		"Hovås IF (U)": 8,
		"Lycksele IF (U)": 8,
		"IFK Arvika": 9,
		"IS Halmia": 9,
		"Södertälje": 9,
		"Ljusdals IF": 9,
		"Norrby IF (U)": 10,
		"IFK Östersund (U)": 10,
		"IFK Ystad (U)": 10,
		"Köpings IS (U)": 10,
		"IFK Härnösand": 11,
		"Hässleholms IF": 11,
		"IFK Värnamo": 11,
		"Malungs IF": 11,
		"Essviks AIF (U)": 12,
		"IK City (U)": 12,
		"Ifö/Bromölla IF": 12,
		"Tidaholms GIF": 12
	},
	{
		"yr": "1971",
		"Gais (N)": 1,
		"Sandvikens IF": 1,
		"Gais": 1,
		"IF Saab": 1,
		"Halmstads BK": 1,
		"Halmstads BK": 2,
		"IK Sirius": 2,
		"IFK Holmsund": 2,
		"Perstorps SK": 2,
		"Jönköpings Södra": 2,
		"IFK Malmö": 3,
		"IK Sleipner": 3,
		"Sandvikens IF": 3,
		"IFK Göteborg (N)": 3,
		"Domsjö IF": 3,
		"IS Halmia": 4,
		"Brynäs IF": 4,
		"IF Saab": 4,
		"Skövde AIK": 4,
		"Nyköpings BIS (U)": 4,
		"IFK Arvika": 5,
		"Älvsjö AIK": 5,
		"IFK Trelleborg": 5,
		"GIF Sundsvall": 5,
		"Kalmar FF": 6,
		"KB Karlskoga": 6,
		"IFK Eskilstuna": 6,
		"Kubikenborgs IF (U)": 6,
		"Skellefteå AIK": 7,
		"IF Brommapojkarna": 7,
		"Blomstermåla IK (U)": 7,
		"Skogens IF (U)": 7,
		"Varbergs BoIS (U)": 8,
		"IK Brage": 8,
		"Grimsås IF": 8,
		"Ljusdals IF": 8,
		"Gnosjö IF (U)": 9,
		"Sandåkerns SK": 9,
		"Västra Frölunda": 9,
		"Södertälje SK": 9,
		"Lycksele IF": 10,
		"Hälsingborgs IF": 10,
		"Degerfors IF": 10,
		"IFK Stockholm": 10,
		"Hovås IF": 11,
		"Nybro IF": 11,
		"IF Vesta (U)": 11,
		"Bodens BK (U)": 11,
		"Gunnarstorps IF (U)": 12,
		"Timrå IK (U)": 12,
		"Råsunda IS (U)": 12,
		"Karlstad BK (U)": 12
	},
	{
		"yr": "1972",
		"IF Saab": 1,
		"IF Elfsborg (N)": 1,
		"IK Sirius": 1,
		"IFK Holmsund": 2,
		"IFK Göteborg": 2,
		"Skövde AIK": 2,
		"GIF Sundsvall": 3,
		"IFK Trelleborg": 3,
		"IFK Eskilstuna": 3,
		"Kalmar FF": 4,
		"Sandvikens IF": 4,
		"Jönköpings Södra": 4,
		"IF Brommapojkarna": 5,
		"Brynäs IF": 5,
		"IS Halmia": 5,
		"Nyköpings BIS": 6,
		"Hässleholms IF (U)": 6,
		"Älvsjö AIK": 6,
		"IFK Malmö": 7,
		"IFK Sundsvall (U)": 7,
		"IK Sleipner": 7,
		"IFK Luleå (N)": 8,
		"KB Karlskoga": 8,
		"Blomstermåla IK": 8,
		"Domsjö IF": 9,
		"IFK Ystad (U)": 9,
		"IFK Arvika": 9,
		"Skogens IF": 10,
		"Gefle IF (U)": 10,
		"BK Derby (U)": 10,
		"Kubikenborgs IF": 11,
		"Kungshamns IF (U)": 11,
		"Spånga IS (U)": 11,
		"Skellefteå AIK": 12,
		"Tidaholms GIF (U)": 12,
		"Perstorps SK": 12
	},
	{
		"yr": "1973",
		"Brynäs IF": 1,
		"Halmstads BK (N)": 1,
		"GIF Sundsvall": 2,
		"Skövde AIK": 2,
		"Kalmar FF": 3,
		"IFK Sundsvall*": 3,
		"Sandvikens IF": 4,
		"IFK Göteborg": 4,
		"Nyköpings BIS": 5,
		"Hässleholms IF": 5,
		"IFK Kristianstad (U)": 6,
		"KB Karlskoga": 6,
		"Degerfors IF (U)": 7,
		"IS Halmia": 7,
		"IFK Eskilstuna": 8,
		"IFK Malmö": 8,
		"Älvsjö AIK": 9,
		"Grimsås IF (U)": 9,
		"Ope IF (U)": 10,
		"Västra Frölunda (U)": 10,
		"IF Brommapojkarna": 11,
		"IK Sleipner": 11,
		"IK Brage (U)": 12,
		"IFK Trelleborg": 12,
		"IFK Luleå*": 13,
		"Blomstermåla IK": 13,
		"IFK Holmsund": 14,
		"Jönköpings Södra": 14
	},
	{
		"yr": "1974",
		"GIF Sundsvall": 1,
		"Örgryte IS (N)": 1,
		"IF Saab (N)": 2,
		"Kalmar FF": 2,
		"IFK Sundsvall": 3,
		"Helsingborgs IF (U)": 3,
		"IFK Malmö": 4,
		"IK Sleipner": 4,
		"IFK Göteborg": 5,
		"IF Brommapojkarna": 5,
		"Grimsås IF": 6,
		"Nyköpings BIS": 6,
		"IS Halmia": 7,
		"KB Karlskoga": 7,
		"IFK Eskilstuna": 8,
		"Emmaboda IS (U)": 8,
		"Skövde AIK": 9,
		"Gefle IF (U)": 9,
		"Västra Frölunda": 10,
		"Sandvikens IF": 10,
		"Ope IF": 11,
		"Trollhättans IF (U)": 11,
		"IFK Kristianstad": 12,
		"Degerfors IF": 12,
		"Älvsjö AIK": 13,
		"Hässleholms IF": 13,
		"IFK Falköping (U)": 14,
		"Skellefteå AIK (U)": 14
	},
	{
		"yr": "1975",
		"IFK Sundsvall": 1,
		"Kalmar FF": 1,
		"IFK Göteborg": 2,
		"Brynäs IF (N)": 2,
		"Helsingborgs IF": 3,
		"IFK Eskilstuna": 3,
		"Jönköpings Södra (U)": 4,
		"IK Sirius (N)": 4,
		"Sandvikens IF": 5,
		"Emmaboda IS": 5,
		"Nyköpings BIS": 6,
		"IS Halmia": 6,
		"IF Saab": 7,
		"KB Karlskoga": 7,
		"IFK Hässleholm (U)": 8,
		"IK Sleipner": 8,
		"Trollhättans IF": 9,
		"Gefle IF": 9,
		"IFK Malmö": 10,
		"BK Derby (U)": 10,
		"Grimsås IF": 11,
		"Ope IF": 11,
		"IF Brommapojkarna": 12,
		"Västra Frölunda": 12,
		"Falu BS (U)": 13,
		"Skövde AIK": 13,
		"Blomstermåla IK (U)": 14,
		"IFK Luleå (U)": 14
	},
	{
		"yr": "1976",
		"BK Derby": 1,
		"IFK Göteborg": 1,
		"Sandvikens IF": 2,
		"Helsingborgs IF": 2,
		"Jönköpings Södra": 3,
		"Västerås SK (U)": 3,
		"Nyköpings BIS": 4,
		"IFK Hässleholm": 4,
		"GIF Sundsvall (N)": 5,
		"Norrby IF (U)": 5,
		"IK Sleipner": 6,
		"Gais (N)": 6,
		"Brynäs IF": 7,
		"IFK Malmö": 7,
		"IFK Eskilstuna": 8,
		"IS Halmia": 8,
		"Hudiksvalls ABK (U)": 9,
		"KB Karlskoga": 9,
		"IK Sirius": 10,
		"Grimsås IF": 10,
		"Råå IF (U)": 11,
		"IF Saab": 11,
		"Ope IF": 12,
		"Motala AIF (U)": 12,
		"Emmaboda IS": 13,
		"Domsjö IF (U)": 13,
		"Gefle IF": 14,
		"Trollhättans IF": 14
	},
	{
		"yr": "1977",
		"Åtvidabergs FF (N)": 1,
		"Västerås SK": 1,
		"Örgryte IS (N)": 2,
		"Sandvikens IF": 2,
		"IK Sirius": 3,
		"Alvesta GIF (U)": 3,
		"Mjällby AIF (U)": 4,
		"Hudiksvalls ABK": 4,
		"IF Brommapojkarna (U)": 5,
		"Helsingborgs IF": 5,
		"IFK Eskilstuna": 6,
		"IS Halmia": 6,
		"Norrby IF": 7,
		"IF Saab": 7,
		"IFK Hässleholm": 8,
		"GIF Sundsvall": 8,
		"Brynäs IF": 9,
		"Gais": 9,
		"Jönköpings Södra": 10,
		"Vasalunds IF (U)": 10,
		"Nyköpings BIS": 11,
		"IFK Malmö": 11,
		"Råå IF": 12,
		"IK Sleipner": 12,
		"KB Karlskoga": 13,
		"IFK Ulricehamn (U)": 13,
		"Grimsås IF": 14,
		"Lycksele IF (U)": 14
	},
	{
		"yr": "1978",
		"IFK Sundsvall (N)": 1,
		"IS Halmia": 1,
		"Norrby IF": 2,
		"IK Brage (U)": 2,
		"BK Häcken (U)": 3,
		"Nyköpings BIS": 3,
		"IFK Eskilstuna": 4,
		"Mjällby AIF": 4,
		"Örgryte IS": 5,
		"BK Derby (N)": 5,
		"GIF Sundsvall": 6,
		"Helsingborgs IF": 6,
		"Gais": 7,
		"IK Sirius": 7,
		"Sandvikens IF": 8,
		"IFK Malmö": 8,
		"Hudiksvalls ABK": 9,
		"Jönköpings Södra": 9,
		"Alvesta GIF": 10,
		"Vasalunds IF": 10,
		"IFK Hässleholm": 11,
		"IFK Västerås (U)": 11,
		"IF Brommapojkarna": 12,
		"Trelleborgs FF (U)": 12,
		"IF Saab": 13,
		"Kramforsalliansen (U)": 13,
		"IFK Kristianstad (U)": 14,
		"Brynäs IF": 14
	},
	{
		"yr": "1979",
		"Mjällby AIF": 1,
		"IK Brage": 1,
		"Helsingborgs IF": 2,
		"Örebro SK (N)": 2,
		"BK Häcken": 3,
		"Degerfors IF (U)": 3,
		"IFK Hässleholm": 4,
		"Västerås SK (N)": 4,
		"Vasalunds IF": 5,
		"Jönköpings Södra": 5,
		"Grimsås IF (U)": 6,
		"Sandvikens IF": 6,
		"IFK Malmö": 7,
		"IFK Eskilstuna": 7,
		"IK Sleipner (U)": 8,
		"GIF Sundsvall": 8,
		"Örgryte IS": 9,
		"Hudiksvalls ABK": 9,
		"Kalmar AIK (U)": 10,
		"Nyköpings BIS": 10,
		"IFK Västerås": 11,
		"Gais": 11,
		"Enköpings SK (U)": 12,
		"Norrby IF": 12,
		"IK Sirius": 13,
		"BK Derby": 13,
		"Gammelstads IF (U)": 14,
		"Alvesta GIF": 14
	},
	{
		"yr": "1980",
		"Örgryte IS": 1,
		"AIK (N)": 1,
		"Örebro SK": 2,
		"Gais": 2,
		"Vasalunds IF": 3,
		"IFK Malmö": 3,
		"Grimsås IF": 4,
		"Karlstad BK (U)": 4,
		"Västerås SK": 5,
		"Helsingborgs IF": 5,
		"BK Häcken": 6,
		"IFK Västerås": 6,
		"Jönköpings Södra": 7,
		"IFK Eskilstuna": 7,
		"IS Halmia (N)": 8,
		"Degerfors IF": 8,
		"GIF Sundsvall": 9,
		"Karlskrona AIF (U)": 9,
		"IFK Hässleholm": 10,
		"Gefle IF/Brynäs (U)": 10,
		"Sandvikens IF": 11,
		"IK Sleipner": 11,
		"IFK Kristianstad (U)": 12,
		"BK Forward (U)": 12,
		"IF Brommapojkarna (U)": 13,
		"Kalmar AIK": 13,
		"Hudiksvalls ABK": 14,
		"Nyköpings BIS (U)": 14
	},
	{
		"yr": "1981",
		"IFK Eskilstuna": 1,
		"BK Häcken": 1,
		"Örebro SK": 2,
		"IS Halmia": 2,
		"Vasalunds IF": 3,
		"Trelleborgs FF": 3,
		"Karlskrona AIF": 4,
		"Flens IF": 4,
		"Mjällby AIF": 5,
		"Västerås SK": 5,
		"Sandvikens IF": 6,
		"Landskrona BoIS": 6,
		"Karlstad BK": 7,
		"Västra Frölunda": 7,
		"Helsingborgs IF": 8,
		"Ope IF": 8,
		"Gefle IF/Brynäs": 9,
		"IK Sleipner": 9,
		"IFK Västerås": 10,
		"IFK Malmö": 10,
		"Degerfors IF": 11,
		"Jönköping Södra": 11,
		"IFK Hässleholm": 12,
		"Karlslunds IF": 12,
		"Spånga IS": 13,
		"Grimsås IF": 13,
		"Gais": 14,
		"GIF Sundsvall": 14
	},
	{
		"yr": "1982",
		"Djurgårdens IF": 1,
		"Mjällby AIF": 1,
		"Gefle IF": 2,
		"BK Häcken": 2,
		"Västra Frölunda": 3,
		"Sandvikens IF": 3,
		"Helsingborgs IF": 4,
		"IFK Sundsvall": 4,
		"Landskrona BoIS": 5,
		"Vasalunds IF": 5,
		"Örebro SK": 6,
		"Trelleborgs FF": 6,
		"IS Halmia": 7,
		"Västerås SK": 7,
		"IFK Malmö": 8,
		"IFK Eskilstuna": 8,
		"Karlskrona AIF": 9,
		"IFK Västerås": 9,
		"Myresjö IF": 10,
		"Ope IF": 10,
		"IK Oddevold": 11,
		"Karlstad BK": 11,
		"IK Sleipner": 12,
		"Flens IF": 12
	},
	{
		"yr": "1983",
		"Kalmar FF": 1,
		"IFK Norrköping": 1,
		"Djurgårdens IF": 2,
		"IFK Malmö": 2,
		"Landskrona BoIS": 3,
		"Örebro SK": 3,
		"Åtvidabergs FF": 4,
		"IF Brommapojkarna": 4,
		"Västerås SK": 5,
		"IS Halmia": 5,
		"Kalmar AIK": 6,
		"Sandvikens IF": 6,
		"Trelleborgs FF": 7,
		"IFK Sundsvall": 7,
		"Myresjö IF": 8,
		"Vasalunds IF": 8,
		"Karlslunds IF": 9,
		"Grimsås IF": 9,
		"IFK Västerås": 10,
		"Västra Frölunda": 10,
		"Helsingborgs IF": 11,
		"IFK Eskilstuna": 11,
		"Karlskrona AIF": 12,
		"Ope IF": 12
	},
	{
		"yr": "1984",
		"Trelleborgs FF": 1,
		"Örebro SK": 1,
		"Mjällby AIF": 2,
		"Åtvidabergs FF": 2,
		"Gais": 3,
		"Djurgårdens IF": 3,
		"IF Brommapojkarna": 4,
		"Helsingborgs IF": 4,
		"IFK Västerås": 5,
		"BK Häcken": 5,
		"Västerås SK": 6,
		"Kalmar AIK": 6,
		"Vasalunds IF": 7,
		"Norrby IF": 7,
		"Karlslunds IF": 8,
		"Västra Frölunda": 8,
		"IFK Malmö": 9,
		"IFK Eskilstuna": 9,
		"Degerfors IF": 10,
		"IS Halmia": 10,
		"Sandvikens IF": 11,
		"Myresjö IF": 11,
		"IFK Sundsvall": 12,
		"Landskrona BoIS": 12,
		"Skellefteå AIK": 13,
		"Lunds BK": 13,
		"Grimsås IF": 14,
		"Nyköpings BIS": 14
	},
	{
		"yr": "1985",
		"IF Elfsborg": 1,
		"Djurgårdens IF": 1,
		"Gais": 2,
		"Västerås SK": 2,
		"Gefle IF": 3,
		"Åtvidabergs FF": 3,
		"Helsingborgs IF": 4,
		"Örebro SK": 4,
		"IFK Eskilstuna": 5,
		"Norrby IF": 5,
		"Luleå FF": 6,
		"Västra Frölunda": 6,
		"IF Brommapojkarna": 7,
		"Kalmar AIK": 7,
		"Sandvikens IF": 8,
		"BK Häcken": 8,
		"Vasalunds IF": 9,
		"Markaryds IF": 9,
		"IFK Västerås": 10,
		"Degerfors IF": 10,
		"Myresjö IF": 11,
		"Ope IF": 11,
		"Jönköpings Södra": 12,
		"Karlslunds IF": 12,
		"IFK Malmö": 13,
		"Tyresö FF": 13,
		"IS Halmia": 14,
		"Falu BS": 14
	},
	{
		"yr": "1986",
		"GIF Sundsvall": 1,
		"Västra Frölunda": 1,
		"Mjällby AIF": 2,
		"IF Brommapojkarna": 2,
		"Västerås SK": 3,
		"Gais": 3,
		"Åtvidabergs FF": 4,
		"Gefle IF": 4,
		"Kalmar AIK": 5,
		"IFK Västerås": 5,
		"Landskrona BoIS": 6,
		"Vasalunds IF": 6,
		"Skellefteå AIK": 7,
		"Trelleborgs FF": 7,
		"Degerfors IF": 8,
		"Karlskrona AIF": 8,
		"IFK Eskilstuna": 9,
		"Karlstad BK": 9,
		"Myresjö IF": 10,
		"Luleå FF/IFK Luleå": 10,
		"BK Häcken": 11,
		"Örebro SK": 11,
		"Helsingborgs IF": 12,
		"Enköpings SK": 12,
		"Markaryds IF": 13,
		"Sandvikens IF": 13,
		"Ope IF": 14,
		"Norrby IF": 14
	},
	{
		"yr": "1987",
		"Djurgårdens IF": 1,
		"Gais": 1,
		"IFK Eskilstuna": 2,
		"Trelleborgs FF": 2,
		"Kalmar AIK": 3,
		"Örebro SK": 3,
		"Gefle IF": 4,
		"Myresjö IF": 4,
		"IK Oddevold": 5,
		"Västerås SK": 5,
		"Åtvidabergs FF": 6,
		"BK Forward": 6,
		"IF Brommapojkarna": 7,
		"Ifö/Bromölla IF": 7,
		"Karlstad BK": 8,
		"Mjällby AIF": 8,
		"Luleå FF/IFK Luleå": 9,
		"BK Häcken": 9,
		"Skellefteå AIK": 10,
		"Landskrona BoIS": 10,
		"IFK Hässleholm": 11,
		"Vasalunds IF": 11,
		"IFK Mora": 12,
		"Karlskrona AIF": 12,
		"IFK Västerås": 13,
		"Kalmar FF": 13,
		"Degerfors IF": 14,
		"Skövde AIK": 14
	},
	{
		"yr": "1988",
		"Halmstads BK": 1,
		"Örebro SK": 1,
		"IFK Eskilstuna": 2,
		"Mjällby AIF": 2,
		"Vasalunds IF": 3,
		"Kalmar AIK": 3,
		"IK Oddevold": 4,
		"Gefle IF": 4,
		"Åtvidabergs FF": 5,
		"BK Häcken": 5,
		"IF Brommapojkarna": 6,
		"Landskrona BoIS": 6,
		"Västerås SK": 7,
		"Karlskrona AIF": 7,
		"Markaryds IF": 8,
		"IFK Holmsund": 8,
		"BK Forward": 9,
		"Trelleborgs FF": 9,
		"IF Elfsborg": 10,
		"Luleå FF/IFK Luleå": 10,
		"Karlstad BK": 11,
		"Ifö/Bromölla IF": 11,
		"Väsby IK": 12,
		"Falkenbergs FF": 12,
		"Skellefteå AIK": 13,
		"Myresjö IF": 13,
		"IFK Hässleholm": 14,
		"IFK Mora": 14
	},
	{
		"yr": "1989",
		"Östers IF": 1,
		"Hammarby IF": 1,
		"Vasalunds IF": 2,
		"Trelleborgs FF": 2,
		"Kiruna FF": 3,
		"IF Elfsborg": 3,
		"IK Oddevold": 4,
		"BK Forward": 4,
		"Kalmar FF": 5,
		"Motala AIF": 5,
		"Mjällby AIF": 6,
		"Luleå FF/IFK Luleå": 6,
		"BK Häcken": 7,
		"Västerås SK": 7,
		"Landskrona BoIS": 8,
		"Gefle IF": 8,
		"IFK Eskilstuna": 9,
		"Markaryds IF": 9,
		"Jonsereds IF": 10,
		"IF Brommapojkarna": 10,
		"Karlskrona AIF": 11,
		"Väsby IK": 11,
		"Kalmar AIK": 12,
		"IFK Holmsund": 12,
		"Åtvidabergs FF": 13,
		"Ifö/Bromölla IF": 13,
		"Falkenbergs FF": 14,
		"Karlstad BK": 14
	},
	{
		"yr": "1990",
		"BK Häcken": 1,
		"GIF Sundsvall": 1,
		"Helsingborgs IF": 2,
		"Vasalunds IF": 2,
		"IF Brommapojkarna": 3,
		"Västra Frölunda": 3,
		"Spårvägens GoIF": 4,
		"Trelleborgs FF": 4,
		"Västerås SK": 5,
		"Jonsereds IF": 5,
		"Kiruna FF": 6,
		"Kalmar AIK": 6,
		"IK Oddevold": 7,
		"IFK Luleå": 7,
		"Kalmar FF": 8,
		"Gefle IF": 8,
		"Markaryds IF": 9,
		"BK Forward": 9,
		"Motala AIF": 10,
		"IF Elfsborg": 10,
		"Gunnilse IS": 11,
		"Väsby IK": 11,
		"IFK Eskilstuna": 12,
		"Landskrona BoIS": 12,
		"Mjällby AIF": 13,
		"IFK Holmsund": 13,
		"Karlskrona AIF": 14,
		"Tyresö FF": 14
	},
	{
		"yr": "1991",
		"IK Brage": 1,
		"Hammarby IF": 1,
		"Västra Frölunda IF": 1,
		"BK Häcken": 1,
		"Helsingborgs IF": 1,
		"Trelleborgs FF": 1,
		"Vasalunds IF": 1,
		"Östers IF": 1,
		"Kiruna FF": 1,
		"Trelleborgs FF": 2,
		"IFK Luleå": 2,
		"BK Forward": 2,
		"Spårvägens FF": 2,
		"Helsingborgs IF": 2,
		"Vasalunds IF": 2,
		"IF Elfsborg": 2,
		"Kalmar FF": 2,
		"Örgryte IS": 2,
		"Myresjö IF": 3,
		"IFK Eskilstuna": 3,
		"IFK Luleå": 3,
		"Gais": 3,
		"IK Oddevold": 3,
		"Kalmar FF": 3,
		"Västerås SK": 3,
		"BK Häcken": 3,
		"BK Forward": 3,
		"Karlskrona AIF": 4,
		"IFK Sundsvall": 4,
		"Skövde AIK": 4,
		"Västra Frölunda IF": 4,
		"Markaryds IF": 4,
		"IK Oddevold": 4,
		"Enköpings SK": 4,
		"Degerfors IF": 4,
		"IK Brage": 4,
		"Jonsereds IF": 5,
		"IK Sirius": 5,
		"Enköpings SK": 5,
		"Väsby IK": 5,
		"Hammarby IF": 5,
		"Mjällby AIF": 5,
		"IF Elfsborg": 5,
		"Väsby IK": 5,
		"Degerfors IF": 5,
		"Motala AIF": 6,
		"Gunnilse IS": 6,
		"Spånga IS": 6,
		"Myresjö IF": 6,
		"IFK Sundsvall": 6,
		"Landskrona BoIS": 6,
		"Spårvägens GoIF": 6,
		"Gunnilse IS": 6,
		"Halmstads BK": 6,
		"Jonsereds IF": 7,
		"GIF Sundsvall": 7,
		"Markaryds IF": 7,
		"IK Sirius": 7,
		"Motala AIF": 7,
		"IFK Eskilstuna": 7,
		"Umeå FC": 7,
		"IK Sleipner": 7,
		"Landskrona BoIS": 7,
		"IF Brommapojkarna": 8,
		"Mjölby AI": 8,
		"Falkenbergs FF": 8,
		"Kiruna FF": 8,
		"Västerås SK": 8,
		"Sandvikens IF": 8,
		"Örgryte IS": 8,
		"Gefle IF": 8,
		"Kalmar AIK": 8
	},
	{
		"yr": "1992",
		"IK Brage": 1,
		"Örgryte IS": 1,
		"Helsingborgs IF": 1,
		"Helsingborgs IF": 1,
		"IFK Luleå": 1,
		"BK Häcken": 1,
		"IFK Sundsvall": 1,
		"Degerfors IF": 1,
		"Halmstads BK": 1,
		"Halmstads BK": 1,
		"IFK Luleå": 2,
		"Vasalunds IF": 2,
		"Vasalunds IF": 2,
		"Hammarby IF": 2,
		"Landskrona BoIS": 2,
		"IFK Luleå": 2,
		"Helsingborgs IF": 2,
		"Örebro SK": 2,
		"Gunnilse IS": 2,
		"IK Oddevold": 2,
		"IF Elfsborg": 3,
		"Örgryte IS": 3,
		"IF Brommapojkarna": 3,
		"IK Brage": 3,
		"Hammarby IF": 3,
		"IF Elfsborg": 3,
		"Landskrona BoIS": 3,
		"IK Sirius": 3,
		"Gefle IF": 3,
		"Kalmar FF": 3,
		"Gunnilse IS": 4,
		"Mälarvik Spårvägens FF": 4,
		"Karlskrona AIF": 4,
		"IK Oddevold": 4,
		"BK Häcken": 4,
		"Mälarvik Spårvägens FF": 4,
		"Degerfors IF": 4,
		"Degerfors IF": 4,
		"Umeå FC": 4,
		"Mjällby AIF": 4,
		"Djurgårdens IF": 5,
		"Tidaholms GIF": 5,
		"Myresjö IF": 5,
		"Kalmar FF": 5,
		"Spånga IS": 5,
		"IFK Eskilstuna": 5,
		"Jonsereds IF": 5,
		"GIF Sundsvall": 5,
		"Gefle IF": 5,
		"Myresjö IF": 6,
		"IFK Hässleholm": 6,
		"BK Forward": 6,
		"GIF Sundsvall": 6,
		"Skövde AIK": 6,
		"IK Sirius": 6,
		"IFK Hässleholm": 6,
		"Gais": 6,
		"Spånga IS": 6,
		"Skövde AIK": 7,
		"Kiruna FF": 7,
		"Gimo IF": 7,
		"BK Forward": 7,
		"Tidaholms GIF": 7,
		"IFK Eskilstuna": 7,
		"Mjällby AIF": 7,
		"Markaryds IF": 7,
		"Västra Frölunda": 7,
		"Karlskrona AIF": 8,
		"IFK Sundsvall": 8,
		"IK Sleipner": 8,
		"Enköpings SK": 8,
		"Väsby IK": 8,
		"Motala AIF": 8,
		"IF Leikin": 8,
		"Kiruna FF": 8,
		"Hertzöga BK": 8
	},
	{
		"yr": "1993",
		"Landskrona BoIS": 1,
		"Hammarby IF": 1,
		"IFK Hässleholm": 2,
		"Vasalunds IF": 2,
		"Djurgårdens IF": 3,
		"Kalmar FF": 3,
		"Spårvägens FF": 4,
		"IF Elfsborg": 4,
		"Gais": 5,
		"IFK Luleå": 5,
		"Jonsereds IF": 6,
		"Gefle IF": 6,
		"Umeå FC": 7,
		"Gunnilse IS": 7,
		"GIF Sundsvall": 8,
		"IK Oddevold": 8,
		"IF Brommapojkarna": 9,
		"BK Forward": 9,
		"Lunds BK": 10,
		"Spånga IS": 10,
		"Myresjö IF": 11,
		"IK Sirius": 11,
		"IFK Uddevalla": 12,
		"Ope IF": 12,
		"Skövde AIK": 13,
		"IFK Sundsvall": 13,
		"Mjällby AIF": 14,
		"Assyriska FF": 14
	},
	{
		"yr": "1994",
		"Djurgårdens IF": 1,
		"Örgryte IS": 1,
		"Kalmar FF": 2,
		"Umeå FC": 2,
		"IFK Hässleholm": 3,
		"IFK Luleå": 3,
		"IF Elfsborg": 4,
		"Vasalunds IF": 4,
		"Gefle IF": 5,
		"IK Oddevold": 5,
		"IK Brage": 6,
		"Gais": 6,
		"Ljungskile SK": 7,
		"GIF Sundsvall": 7,
		"IF Brommapojkarna": 8,
		"Gunnilse IS": 8,
		"IK Sirius": 9,
		"Stenungsunds IF": 9,
		"Västerås SK": 10,
		"BK Forward": 10,
		"Visby IF Gute": 11,
		"Jonsereds IF": 11,
		"Spånga IS": 12,
		"Karlskrona AIF": 12,
		"Kiruna FF": 13,
		"IK Sleipner": 13,
		"Spårvägens FF": 14,
		"Lunds BK": 14
	},
	{
		"yr": "1995",
		"Umeå FC": 1,
		"IK Oddevold": 1,
		"Gais": 2,
		"Gefle IF": 2,
		"Vasalunds IF": 3,
		"IF Elfsborg": 3,
		"Visby IF Gute": 4,
		"Kalmar FF": 4,
		"IK Brage": 5,
		"Ljungskile SK": 5,
		"IFK Luleå": 6,
		"Gunnilse IS": 6,
		"BK Häcken": 7,
		"GIF Sundsvall": 7,
		"IF Brommapojkarna": 8,
		"IFK Hässleholm": 8,
		"Falkenbergs FF": 9,
		"Västerås SK": 9,
		"Stenungsunds IF": 10,
		"BK Forward": 10,
		"IK Sirius": 11,
		"Norrby IF": 11,
		"Myresjö IF": 12,
		"Assyriska FF": 12,
		"Skövde AIK": 13,
		"Väsby IK": 13,
		"Landskrona BoIS": 14,
		"Lira Luleå": 14
	},
	{
		"yr": "1996",
		"IF Elfsborg": 1,
		"Västerås SK": 1,
		"Ljungskile SK": 2,
		"Hammarby IF": 2,
		"Stenungsunds IF": 3,
		"Spårvägens FF": 3,
		"GIF Sundsvall": 4,
		"BK Häcken": 4,
		"Mjällby AIF": 5,
		"IF Brommapojkarna": 5,
		"IFK Hässleholm": 6,
		"IK Brage": 6,
		"Gunnilse IS": 7,
		"Gefle IF": 7,
		"Västra Frölunda": 8,
		"Hertzöga BK": 8,
		"Motala AIF": 9,
		"IFK Luleå": 9,
		"Åtvidabergs FF": 10,
		"Vasalunds IF": 10,
		"Visby IF Gute": 11,
		"Falkenbergs FF": 11,
		"Lundby IF": 12,
		"IK Sirius": 12,
		"BK Forward": 13,
		"Gais": 13,
		"Gimonäs CK": 14,
		"Kalmar FF": 14
	},
	{
		"yr": "1997",
		"Hammarby IF": 1,
		"Västra Frölunda": 1,
		"Djurgårdens IF": 2,
		"BK Häcken": 2,
		"Gunnilse IS": 3,
		"Umeå FC": 3,
		"Åtvidabergs FF": 4,
		"GIF Sundsvall": 4,
		"Gefle IF": 5,
		"Stenungsunds IF": 5,
		"Nacka FF": 6,
		"Mjällby AIF": 6,
		"IFK Hässleholm": 7,
		"IFK Luleå": 7,
		"Motala AIF": 8,
		"IK Brage": 8,
		"Assyriska FF": 9,
		"Falkenbergs FF": 9,
		"Norrby IF": 10,
		"Spårvägens FF": 10,
		"Lira Luleå": 11,
		"Hertzöga BK": 11,
		"Myresjö IF": 12,
		"Enköpings SK": 12,
		"IFK Malmö": 13,
		"IF Brommapojkarna": 13,
		"Vasalunds IF": 14,
		"IK Oddevold": 14
	},
	{
		"yr": "1998",
		"Djurgårdens IF": 1,
		"Kalmar FF": 1,
		"Landskrona BoIS": 2,
		"Umeå FC": 2,
		"Västerås SK": 3,
		"IF Sylvia": 3,
		"Åtvidabergs FF": 4,
		"GIF Sundsvall": 4,
		"Stenungsunds IF": 5,
		"Assyriska FF": 5,
		"Ljungskile SK": 6,
		"IK Brage": 6,
		"IK Sirius": 7,
		"Falkenbergs FF": 7,
		"Degerfors IF": 8,
		"Gunnilse IS": 8,
		"Mjällby AIF": 9,
		"Nacka FF": 9,
		"Spårvägens FF": 10,
		"Motala AIF": 10,
		"Norrby IF": 11,
		"Gefle IF": 11,
		"Piteå IF": 12,
		"IFK Hässleholm": 12,
		"Ludvika FK": 13,
		"Lundby IF": 13,
		"IS Halmia": 14,
		"IFK Luleå": 14
	},
	{
		"yr": "1999",
		"BK Häcken": 1,
		"GIF Sundsvall": 1,
		"Assyriska FF": 2,
		"Gais": 2,
		"Mjällby AIF": 3,
		"IF Sylvia": 3,
		"Enköpings SK": 4,
		"Ljungskile SK": 4,
		"IK Brage": 5,
		"Landskrona BoIS": 5,
		"Gunnilse IS": 6,
		"Västerås SK": 6,
		"Umeå FC": 7,
		"Åtvidabergs FF": 7,
		"Östers IF": 8,
		"Gefle IF": 8,
		"Kristianstads FF": 9,
		"Degerfors IF": 9,
		"IK Kongahälla": 10,
		"IF Brommapojkarna": 10,
		"Nacka FF": 11,
		"Husqvarna FF": 11,
		"Lira BK": 12,
		"Falkenbergs FF": 12,
		"IK Sirius": 13,
		"Motala AIF": 13,
		"Stenungsunds IF": 14,
		"Spårvägens FF": 14
	},
	{
		"yr": "2000",
		"Djurgårdens IF": 1,
		"Malmö FF": 2,
		"Mjällby AIF": 3,
		"Landskrona BoIS": 4,
		"Västerås SK": 5,
		"Café Opera": 6,
		"Enköpings SK": 7,
		"IK Brage": 8,
		"IF Sylvia": 9,
		"Kalmar FF": 10,
		"Assyriska FF": 11,
		"Östers IF": 12,
		"Umeå FC": 13,
		"Åtvidabergs FF": 14,
		"Ljungskile SK": 15,
		"Gunnilse IS": 16
	},
	{
		"yr": "2001",
		"Kalmar FF": 1,
		"Landskrona BoIS": 2,
		"Mjällby AIF": 3,
		"Gefle IF": 4,
		"Café Opera": 5,
		"Västerås SK": 6,
		"IF Sylvia": 7,
		"Enköpings SK": 8,
		"Västra Frölunda": 9,
		"IK Brage": 10,
		"IFK Malmö": 11,
		"Östers IF": 12,
		"Assyriska FF": 13,
		"Gais": 14,
		"Umeå FC": 15,
		"Motala AIF": 16
	},
	{
		"yr": "2002",
		"Östers IF": 1,
		"Enköpings SK": 2,
		"Västra Frölunda": 3,
		"BK Häcken": 4,
		"Assyriska FF": 5,
		"Café Opera": 6,
		"IFK Malmö": 7,
		"Västerås SK": 8,
		"Trelleborgs FF": 9,
		"Åtvidabergs FF": 10,
		"Gefle IF": 11,
		"IF Brommapojkarna": 12,
		"IF Sylvia": 13,
		"IK Brage": 14,
		"Ängelholms FF": 15,
		"Mjällby AIF": 16
	},
	{
		"yr": "2003",
		"Kalmar FF": 1,
		"Trelleborgs FF": 2,
		"BK Häcken": 3,
		"Åtvidabergs FF": 4,
		"Västra Frölunda": 5,
		"IF Brommapojkarna": 6,
		"Café Opera": 7,
		"Gefle IF": 8,
		"IFK Norrköping": 9,
		"Assyriska FF": 10,
		"Bodens BK": 11,
		"Västerås SK": 12,
		"Falkenbergs FF": 13,
		"IFK Malmö": 14,
		"BK Forward": 15,
		"IF Sylvia": 16
	},
	{
		"yr": "2004",
		"BK Häcken": 1,
		"Gefle IF": 2,
		"Assyriska FF": 3,
		"IFK Norrköping": 4,
		"Östers IF": 5,
		"Gais": 6,
		"Åtvidabergs FF": 7,
		"Västerås SK": 8,
		"Café Opera": 9,
		"IF Brommapojkarna": 10,
		"Västra Frölunda": 11,
		"Falkenbergs FF": 12,
		"Bodens BK": 13,
		"Enköpings SK": 14,
		"IK Brage": 15,
		"Friska Viljor": 16
	},
	{
		"yr": "2005",
		"AIK": 1,
		"Östers IF": 2,
		"Gais": 3,
		"Ljungskile SK": 4,
		"Örebro SK": 5,
		"IF Brommapojkarna": 6,
		"IFK Norrköping": 7,
		"Falkenbergs FF": 8,
		"Väsby United": 9,
		"Åtvidabergs FF": 10,
		"Trelleborgs FF": 11,
		"Mjällby AIF": 12,
		"Degerfors IF": 13,
		"Bodens BK": 14,
		"Västerås SK": 15,
		"Västra Frölunda": 16
	},
	{
		"yr": "2006",
		"Trelleborgs FF": 1,
		"Örebro SK": 2,
		"IF Brommapojkarna": 3,
		"IFK Norrköping": 4,
		"Landskrona BoIS": 5,
		"Ljungskile SK": 6,
		"Mjällby AIF": 7,
		"GIF Sundsvall": 8,
		"Falkenbergs FF": 9,
		"Jönköpings Södra": 10,
		"Degerfors IF": 11,
		"Åtvidabergs FF": 12,
		"Assyriska FF": 13,
		"Väsby United": 14,
		"Qviding FIF": 15,
		"Umeå FC": 16
	},
	{
		"yr": "2007",
		"IFK Norrköping": 1,
		"Ljungskile SK": 2,
		"GIF Sundsvall": 3,
		"BK Häcken": 4,
		"Bunkeflo IF": 5,
		"Åtvidabergs FF": 6,
		"IK Sirius": 7,
		"Degerfors IF": 8,
		"Mjällby AIF": 9,
		"Örgryte IS": 10,
		"Landskrona BoIS": 11,
		"Enköpings SK": 12,
		"Jönköpings Södra": 13,
		"Falkenbergs FF": 14,
		"Östers IF": 15,
		"IF Sylvia": 16
	},
	{
		"yr": "2008",
		"Örgryte IS": 1,
		"BK Häcken": 2,
		"IF Brommapojkarna": 3,
		"Assyriska FF": 4,
		"Ängelholms FF": 5,
		"Åtvidabergs FF": 6,
		"Falkenbergs FF": 7,
		"Mjällby AIF": 8,
		"Väsby United": 9,
		"Qviding FIF": 10,
		"Landskrona BoIS": 11,
		"IK Sirius": 12,
		"Limhamn Bunkeflo": 13,
		"Jönköpings Södra": 14,
		"Enköpings SK": 15,
		"Degerfors IF": 16
	},
	{
		"yr": "2009",
		"Mjällby AIF": 1,
		"Åtvidabergs FF": 2,
		"Assyriska FF": 3,
		"Syrianska FC": 4,
		"GIF Sundsvall": 5,
		"Falkenbergs FF": 6,
		"Ängelholms FF": 7,
		"Landskrona BoIS": 8,
		"Ljungskile SK": 9,
		"Jönköpings Södra": 10,
		"IFK Norrköping": 11,
		"Väsby United": 12,
		"FC Trollhättan": 13,
		"Qviding FIF": 14,
		"IK Sirius": 15,
		"Vasalunds IF": 16
	},
	{
		"yr": "2010",
		"Syrianska FC": 1,
		"IFK Norrköping": 2,
		"GIF Sundsvall": 3,
		"Assyriska FF": 4,
		"Landskrona BoIS": 5,
		"Ljungskile SK": 6,
		"Falkenbergs FF": 7,
		"Hammarby IF": 8,
		"Örgryte IS": 9,
		"Degerfors IF": 10,
		"IK Brage": 11,
		"Ängelholms FF": 12,
		"Jönköpings Södra": 13,
		"Östers IF": 14,
		"FC Trollhättan": 15,
		"Väsby United": 16
	},
	{
		"yr": "2011",
		"Åtvidabergs FF": 1,
		"GIF Sundsvall": 2,
		"Ängelholms FF": 3,
		"Östers IF": 4,
		"Degerfors IF": 5,
		"IF Brommapojkarna": 6,
		"Falkenbergs FF": 7,
		"Ljungskile SK": 8,
		"Assyriska FF": 9,
		"Landskrona BoIS": 10,
		"Hammarby IF": 11,
		"Jönköpings Södra": 12,
		"IFK Värnamo": 13,
		"IK Brage": 14,
		"Västerås SK": 15,
		"Qviding FIF": 16
	},
	{
		"yr": "2012",
		"Östers IF": 1,
		"IF Brommapojkarna": 2,
		"Halmstads BK": 3,
		"Hammarby IF": 4,
		"Ljungskile SK": 5,
		"Landskrona BoIS": 6,
		"Jönköpings Södra": 7,
		"Assyriska FF": 8,
		"Ängelholms FF": 9,
		"IK Brage": 10,
		"Varbergs BoIS": 11,
		"Degerfors IF": 12,
		"Falkenbergs FF": 13,
		"IFK Värnamo": 14,
		"Trelleborgs FF": 15,
		"Umeå FC": 16
	},
	{
		"yr": "2013",
		"Falkenbergs FF": 1,
		"Örebro SK": 2,
		"GIF Sundsvall": 3,
		"Degerfors IF": 4,
		"Hammarby IF": 5,
		"Ängelholms FF": 6,
		"Gais": 7,
		"Assyriska FF": 8,
		"Ljungskile SK": 9,
		"Östersunds FK": 10,
		"Jönköpings Södra IF": 11,
		"Landskrona BoIS": 12,
		"Varbergs BoIS": 13,
		"IFK Värnamo": 14,
		"Örgryte IS": 15,
		"IK Brage": 16,
		"Hammarby IF": null,
		"Jönköpings Södra IF": null,
		"Assyriska FF": null,
		"Örebro SK": null,
		"Östersunds FK": null,
		"Varbergs BoIS": null,
		"Degerfors IF": null,
		"IFK Värnamo": null,
		"Gais": null,
		"Falkenbergs FF": null,
		"IK Brage": null,
		"GIF Sundsvall": null,
		"Örgryte IS": null,
		"Landskrona BoIS": null,
		"Hammarby IF": null,
		"Ängelholms FF": null,
		"Ljungskile SK": null
	},
	{
		"yr": "2014",
		"Hammarby IF": 1,
		"GIF Sundsvall": 2,
		"Ljungskile SK": 3,
		"Jönköpings Södra IF": 4,
		"Östersunds FK": 5,
		"IK Sirius (U)": 6,
		"Degerfors IF": 7,
		"Varbergs BoIS": 8,
		"IFK Värnamo": 9,
		"Syrianska FC (N)": 10,
		"Gais": 11,
		"Ängelholms FF": 12,
		"Östers IF (N)": 13,
		"Assyriska FF": 14,
		"Landskrona BoIS": 15,
		"Husqvarna FF (U)": 16
	},
	{
		"yr": "2015",
		"Jönköpings Södra": 1,
		"Östersunds FK": 2,
		"IK Sirius": 3,
		"Assyriska FF": 4,
		"Varbergs BoIS": 5,
		"Ljungskile SK": 6,
		"Syrianska FC": 7,
		"AFC United (U)": 8,
		"Degerfors IF": 9,
		"IFK Värnamo": 10,
		"Gais": 11,
		"Ängelholms FF": 12,
		"Mjällby AIF (N)": 13,
		"IK Frej (U)": 14,
		"Utsiktens BK (U)": 15,
		"IF Brommapojkarna (N)": 16
	},
	{
		"yr": "1957/1958",
		"Landskrona BoIS": 1,
		"Örgryte IS": 1,
		"Skellefteå AIK": 1,
		"Hammarby IF (N)": 1,
		"Råå IF": 2,
		"Degerfors IF": 2,
		"IF Elfsborg": 2,
		"IFK Holmsund": 2,
		"IFK Kristianstad": 3,
		"Örebro SK": 3,
		"Marma IF (U)": 3,
		"Norrby IF": 3,
		"GIF Sundsvall": 4,
		"BK Derby": 4,
		"IK Brage": 4,
		"Jönköpings Södra": 4,
		"Lycksele IF": 5,
		"Köpings IS": 5,
		"IK Sleipner": 5,
		"IK Oddevold": 5,
		"IFK Luleå": 6,
		"Kinna IF": 6,
		"Västerås SK (N)": 6,
		"Höganäs BK": 6,
		"Husqvarna IF": 7,
		"Kalmar FF": 7,
		"IFK Stockholm": 7,
		"IFK Östersund (U)": 7,
		"SK Sifhälla (U)": 8,
		"Waggeryds IK": 8,
		"Gefle IF": 8,
		"Katrineholms SK": 8,
		"IS Halmia": 9,
		"Åtvidabergs FF": 9,
		"Hallstahammars SK (U)": 9,
		"Bodens BK": 9,
		"Tranemo IF (U)": 10,
		"IF Saab (U)": 10,
		"Skellefteå IF (U)": 10,
		"Vasalunds IF (U)": 10,
		"Jonsereds IF (U)": 11,
		"IF Allians (U)": 11,
		"IFK Bofors": 11,
		"Tidaholms GIF (U)": 12,
		"Kalmar AIK (U)": 12,
		"Surahammars IF": 12
	},
	{
		"yr": "1956/1957",
		"IFK Eskilstuna": 1,
		"GIF Sundsvall": 1,
		"Motala AIF": 1,
		"Landskrona BoIS": 2,
		"Örebro SK": 2,
		"Skellefteå AIK": 2,
		"BK Derby": 3,
		"IFK Holmsund": 3,
		"IFK Stockholm": 3,
		"Degerfors IF (N)": 4,
		"Höganäs BK": 4,
		"Bodens BK": 4,
		"IK Sleipner": 5,
		"Lycksele IF": 5,
		"IK Brage": 5,
		"IFK Kristianstad (U)": 6,
		"Köpings IS": 6,
		"IFK Luleå (U)": 6,
		"Åtvidabergs FF": 7,
		"Katrineholms SK (U)": 7,
		"Gefle IF (U)": 7,
		"Friska Viljor (U)": 8,
		"Råå IF": 8,
		"IFK Bofors (U)": 8,
		"Kalmar FF": 9,
		"Fagerviks GF": 9,
		"Surahammars IF": 9,
		"Ljusne AIK": 10,
		"IK City": 10,
		"Nybro IF": 10,
		"BK Kenty (U)": 11,
		"Avesta AIK (U)": 11,
		"Karlstads BIK": 12,
		"Gunnarstorps IF (U)": 12
	},
	{
		"yr": "1955/1956",
		"IFK Malmö": 1,
		"Lycksele IF": 1,
		"IK Brage": 1,
		"Kalmar FF (N)": 2,
		"Fagerviks GF": 2,
		"Örebro SK": 2,
		"Bodens BK (U)": 3,
		"Motala AIF": 3,
		"IK City": 3,
		"BK Derby": 4,
		"IFK Holmsund": 4,
		"IFK Stockholm (U)": 4,
		"Skellefteå AIK": 5,
		"IK Sleipner": 5,
		"IFK Eskilstuna": 5,
		"Karlstads BIK": 6,
		"GIF Sundsvall (U)": 6,
		"Nybro IF": 6,
		"Ljusne AIK": 7,
		"Landskrona BoIS": 7,
		"Surahammars IF (U)": 7,
		"Åtvidabergs FF": 8,
		"IFK Östersund": 8,
		"Köpings IS": 8,
		"Sandvikens AIK (N)": 9,
		"SK Sifhälla (U)": 9,
		"Trelleborgs FF (U)": 9,
		"IFK Trelleborg": 10,
		"Sollefteå GIF (U)": 10,
		"Karlskoga IF": 10
	},
	{
		"yr": "1954/1955",
		"Norrby IF": 1,
		"Sandvikens IF (N)": 1,
		"Västerås SK": 1,
		"IFK Malmö": 2,
		"IFK Eskilstuna": 2,
		"Lycksele IF": 2,
		"Fagerviks GF": 3,
		"IF Elfsborg (N)": 3,
		"Motala AIF": 3,
		"Råå IF": 4,
		"IFK Östersund": 4,
		"IK City": 4,
		"Jönköpings Södra (N)": 5,
		"Ljusne AIK": 5,
		"Örebro SK": 5,
		"Köpings IS (U)": 6,
		"Skellefteå AIK": 6,
		"BK Derby": 6,
		"IFK Holmsund (U)": 7,
		"Karlstads BIK (U)": 7,
		"Höganäs BK": 7,
		"Friska Viljor (U)": 8,
		"Landskrona BoIS": 8,
		"IK Brage": 8,
		"IFK Trelleborg": 9,
		"Karlskoga IF": 9,
		"IF Älgarna": 9,
		"Södertälje SK (U)": 10,
		"Skutskärs IF (U)": 10,
		"Nybro IF (U)": 10,
		"Kinna IF (U)": 11,
		"IK Sleipner": 12,
		"Åtvidabergs FF": 13,
		"IS Halmia (U)": 14
	},
	{
		"yr": "1953/1954",
		"Sandvikens AIK (U)": 1,
		"Halmstads BK": 1,
		"Hammarby IF": 1,
		"IK Sleipner (U)": 2,
		"Ljusne AIK (U)": 2,
		"Örebro SK (N)": 2,
		"Lycksele IF (U)": 3,
		"IFK Eskilstuna (U)": 3,
		"Norrby IF": 3,
		"Skellefteå AIK (U)": 4,
		"IK Brage": 4,
		"IFK Malmö (N)": 4,
		"Landskrona BoIS (U)": 5,
		"Karlskoga IF (U)": 5,
		"IFK Östersund (U)": 5,
		"BK Derby": 6,
		"IK City": 6,
		"Fagerviks GF (U)": 6,
		"Västerås SK": 7,
		"Åtvidabergs FF": 7,
		"IF Älgarna (U)": 7,
		"Västerås IK (U)": 8,
		"GIF Sundsvall (U)": 8,
		"Råå IF": 8,
		"Falu BS (U)": 9,
		"Sollefteå GIF (U)": 9,
		"Höganäs BK": 9,
		"IFK Trelleborg": 10,
		"Ljunga IF (U)": 10,
		"Avesta AIK (U)": 10,
		"Motala AIF": 11,
		"BK Häcken": 12,
		"Örgryte IS": 13,
		"Redbergslids IK (U)": 14
	},
	{
		"yr": "1952/1953",
		"Sandvikens IF": 1,
		"Kalmar FF": 1,
		"Höganäs BK": 2,
		"IK City": 2,
		"Motala AIF": 3,
		"Norrby IF": 3,
		"Halmstads BK": 4,
		"Åtvidabergs FF (N)": 4,
		"Örgryte IS (U)": 5,
		"BK Derby (U)": 5,
		"Råå IF (N)": 6,
		"Hammarby IF": 6,
		"Västerås SK (U)": 7,
		"BK Häcken": 7,
		"IFK Trelleborg (U)": 8,
		"IK Brage": 8,
		"Karlstads BIK": 9,
		"Lunds BK": 9,
		"IS Halmia": 10,
		"IF Viken": 10
	},
	{
		"yr": "1951/1952",
		"AIK (N)": 1,
		"IFK Malmö": 1,
		"Halmstads BK": 2,
		"Karlstads BIK": 2,
		"Sandvikens IF": 3,
		"Norrby IF": 3,
		"Lunds BK": 4,
		"Hammarby IF": 4,
		"BK Häcken (U)": 5,
		"Motala AIF (U)": 5,
		"Kalmar FF (N)": 6,
		"IF Viken": 6,
		"IK City": 7,
		"IS Halmia": 7,
		"IK Brage": 8,
		"Höganäs BK": 8,
		"Landskrona BoIS": 9,
		"Sandvikens AIK": 9,
		"Ludvika FFI (U)": 10,
		"Ronneby BK (U)": 10
	},
	{
		"yr": "1950/1951",
		"Åtvidabergs FF": 1,
		"IFK Göteborg (N)": 1,
		"Sandvikens IF (U)": 2,
		"IFK Malmö": 2,
		"IS Halmia (N)": 3,
		"IF Viken": 3,
		"Lunds BK (U)": 4,
		"Hammarby IF (U)": 4,
		"Landskrona BoIS": 5,
		"IK City": 5,
		"Norrby IF (U)": 6,
		"Sandvikens AIK": 6,
		"IK Brage": 7,
		"Halmstads BK": 7,
		"Karlstads BIK": 8,
		"Höganäs BK": 8,
		"Örgryte IS": 9,
		"Karlskoga IF": 9,
		"Huskvarna Södra": 10,
		"Surahammars IF": 10
	},
	{
		"yr": "1949/1950",
		"Råå IF": 1,
		"Örebro SK (N)": 1,
		"Halmstads BK": 2,
		"Surahammars IF": 2,
		"Landskrona BoIS (N)": 3,
		"IK City (U)": 3,
		"Karlstads BIK": 4,
		"Örgryte IS": 4,
		"Huskvarna Södra (U)": 5,
		"IF Viken (U)": 5,
		"Höganäs BK": 6,
		"Karlskoga IF": 6,
		"Åtvidabergs FF": 7,
		"IK Brage (U)": 7,
		"Sandvikens AIK": 8,
		"IFK Malmö": 8,
		"Jonsereds IF": 9,
		"Sundbybergs IK": 9,
		"IK Sleipner": 10,
		"Reymersholms IK": 10
	},
	{
		"yr": "1948/1949",
		"Kalmar FF": 1,
		"Djurgårdens IF (N)": 1,
		"Åtvidabergs FF": 2,
		"IFK Malmö": 2,
		"Sundbybergs IK (U)": 3,
		"Halmstads BK (N)": 3,
		"IK Sleipner": 4,
		"Höganäs BK": 4,
		"Råå IF (U)": 5,
		"Surahammars IF": 5,
		"Örgryte IS": 6,
		"Sandvikens AIK": 6,
		"Karlskoga IF": 7,
		"Jonsereds IF (U)": 7,
		"Reymersholms IK": 8,
		"Karlstads BIK": 8,
		"Sandvikens IF (U)": 9,
		"Tidaholms GIF": 9,
		"Ludvika FFI": 10,
		"Billingsfors IK": 10
	},
	{
		"yr": "1947/1948",
		"Örebro SK (N)": 1,
		"Landskrona BoIS": 1,
		"Karlstads BIK": 2,
		"Örgryte IS": 2,
		"Tidaholms GIF": 3,
		"Ludvika FFI": 3,
		"Åtvidabergs FF": 4,
		"Sandvikens AIK": 4,
		"Reymersholms IK": 5,
		"Kalmar FF": 5,
		"Surahammars IF": 6,
		"IFK Malmö": 6,
		"Höganäs BK": 7,
		"Karlskoga IF": 7,
		"IK Sleipner": 8,
		"Billingsfors IK (N)": 8,
		"Husqvarna IF": 9,
		"Västerås IK": 9,
		"IFK Västerås": 10,
		"IFK Uddevalla": 10
	},
	{
		"yr": "1946/1947",
		"Halmstads BK (N)": 1,
		"Örgryte IS": 1,
		"Ludvika FFI": 1,
		"Tidaholms GIF": 2,
		"Landskrona BoIS": 2,
		"Sandvikens AIK": 2,
		"IFK Malmö": 3,
		"IFK Uddevalla": 3,
		"Surahammars IF": 3,
		"Kalmar FF": 4,
		"Västerås IK": 4,
		"Karlstads BIK": 4,
		"Höganäs BK (U)": 5,
		"IFK Västerås": 5,
		"Karlskoga IF": 5,
		"IK Brage": 6,
		"Lundby IF": 6,
		"Kalmar AIK": 6,
		"Olofströms IF (U)": 7,
		"IFK Trollhättan (U)": 7,
		"Sandvikens IF": 7,
		"Malmö BI": 8,
		"Göteborgs FF": 8,
		"Avesta AIK": 8,
		"IF Viken (U)": 9,
		"Nybro IF": 9,
		"Iggesunds IK (U)": 9,
		"Deje IK": 10,
		"Enköpings SK (U)": 10,
		"Alets IK": 10
	},
	{
		"yr": "1945/1946",
		"Örebro SK": 1,
		"Surahammars IF": 1,
		"Landskrona BoIS (N)": 1,
		"Billingsfors IK": 1,
		"Åtvidabergs FF": 2,
		"Avesta AIK": 2,
		"Tidaholms GIF": 2,
		"Husqvarna IF": 2,
		"IFK Malmö": 3,
		"IFK Västerås": 3,
		"IK Sleipner": 3,
		"Lundby IF": 3,
		"Kalmar FF": 4,
		"Deje IK (U)": 4,
		"IK Brage": 4,
		"Hammarby IF": 4,
		"Västerås IK (U)": 5,
		"IFK Eskilstuna": 5,
		"IFK Uddevalla": 5,
		"Nybro IF": 5,
		"Ludvika FFI (N)": 6,
		"Kalmar AIK (U)": 6,
		"Reymersholms IK": 6,
		"Örgryte IS": 6,
		"Alets IK": 7,
		"Göteborgs FF (U)": 7,
		"Sandvikens IF": 7,
		"BK Derby (U)": 7,
		"Malmö BI (U)": 8,
		"Karlskoga IF": 8,
		"Sandvikens AIK": 8,
		"Karlstads BIK": 8,
		"Limhamns IF": 9,
		"Sundbybergs IK": 9,
		"IFK Tidaholm": 9,
		"Ljusne AIK": 9,
		"Hagalunds IS (U)": 10,
		"Gårda BK": 10,
		"Blomstermåla IF": 10,
		"Långshyttans AIK (U)": 10
	},
	{
		"yr": "1944/1945",
		"Tidaholms GIF": 1,
		"Djurgårdens IF": 1,
		"Åtvidabergs FF": 1,
		"Örgryte IS": 2,
		"Hammarby IF": 2,
		"Surahammars IF (U)": 2,
		"Reymersholms IK": 3,
		"Karlstads BIK (U)": 3,
		"IFK Västerås": 3,
		"Sundbybergs IK (U)": 4,
		"IFK Tidaholm (U)": 4,
		"IK Brage (N)": 4,
		"IK Sleipner": 5,
		"Lundby IF": 5,
		"Sandvikens IF (N)": 5,
		"IFK Eskilstuna": 6,
		"Gårda BK": 6,
		"Sandvikens AIK": 6,
		"Karlskoga IF": 7,
		"Billingsfors IK": 7,
		"Avesta AIK (U)": 7,
		"IFK Uddevalla": 8,
		"Örebro SK": 8,
		"Ljusne AIK": 8,
		"IFK Trollhättan": 9,
		"IF Verdandi": 9,
		"Hallstahammars SK": 9,
		"Gefle IF": 10,
		"Skogens IF": 10,
		"Nyköpings AIK": 10
	},
	{
		"yr": "1943/1944",
		"IFK Eskilstuna (N)": 1,
		"Billingsfors IK": 1,
		"Örgryte IS": 2,
		"IK Sleipner": 2,
		"Karlskoga IF": 3,
		"Tidaholms GIF": 3,
		"IFK Västerås": 4,
		"IFK Uddevalla": 4,
		"Örebro SK": 5,
		"Gårda BK (N)": 5,
		"IFK Trollhättan": 6,
		"Åtvidabergs FF": 6,
		"IF Verdandi": 7,
		"Lundby IF": 7,
		"Nyköpings AIK": 8,
		"Skogens IF": 8,
		"Finspångs AIK": 9,
		"Munkedals IF (U)": 9,
		"Västerås SK (U)": 10,
		"Krokslätts FF (U)": 10
	},
	{
		"yr": "1942/1943",
		"Finspångs AIK": 1,
		"IS Halmia": 1,
		"Örgryte IS": 1,
		"IK Brage": 1,
		"Sandvikens AIK": 2,
		"Åtvidabergs FF": 2,
		"Karlskoga IF": 2,
		"Landskrona BoIS (N)": 2,
		"Ludvika FFI": 3,
		"IFK Trollhättan (U)": 3,
		"Nybro IF": 3,
		"Nyköpings AIK (U)": 3,
		"Billingsfors IK": 4,
		"Hammarby IF": 4,
		"Örebro SK": 4,
		"IFK Malmö": 4,
		"Skogens IF": 5,
		"Hallstahammars SK": 5,
		"Reymersholms IK (N)": 5,
		"Bromölla IF (U)": 5,
		"Höganäs BK": 6,
		"IF Verdandi (U)": 6,
		"Djurgårdens IF": 6,
		"IFK Uddevalla (U)": 6,
		"Tidaholms GIF": 7,
		"Olofströms IF": 7,
		"Hagalunds IS (U)": 7,
		"IK Sleipner": 7,
		"BK Landora": 8,
		"Lundby IF": 8,
		"Gefle IF": 8,
		"IFK Västerås": 8,
		"Surahammars IF": 9,
		"IFK Trelleborg": 9,
		"Deje IK": 9,
		"Hofors AIF": 9,
		"Waggeryds IK": 10,
		"Sundbybergs IK": 10,
		"Varbergs BoIS (U)": 10,
		"Avesta AIK (U)": 10
	},
	{
		"yr": "1941/1942",
		"Lundby IF": 1,
		"IK Brage (N)": 1,
		"Halmstads BK": 1,
		"IFK Eskilstuna": 1,
		"Surahammars IF": 2,
		"Tidaholms GIF": 2,
		"Hammarby IF": 2,
		"IS Halmia": 2,
		"Sandvikens AIK": 3,
		"Höganäs BK": 3,
		"IK Sleipner (N)": 3,
		"Örgryte IS": 3,
		"Örebro SK": 4,
		"Nybro IF (U)": 4,
		"Karlskoga IF": 4,
		"Hofors AIF": 4,
		"Billingsfors IK": 5,
		"Hallstahammars SK": 5,
		"Djurgårdens IF": 5,
		"BK Landora": 5,
		"Skogens IF (U)": 6,
		"Olofströms IF": 6,
		"Finspångs AIK": 6,
		"Ludvika FFI": 6,
		"Waggeryds IK (U)": 7,
		"IFK Västerås": 7,
		"Sundbybergs IK": 7,
		"IFK Trelleborg (U)": 7,
		"Gefle IF": 8,
		"Deje IK": 8,
		"IFK Malmö": 8,
		"Åtvidabergs FF": 8,
		"IK City (U)": 9,
		"Kalmar AIK": 9,
		"Ljusne AIK (U)": 9,
		"Karlstads BIK (U)": 9,
		"Skara IF": 10,
		"Mjölby AIF": 10,
		"IFK Lidingö (U)": 10,
		"IFK Kristianstad": 10
	},
	{
		"yr": "1940/1941",
		"Reymersholms IK": 1,
		"Gais": 1,
		"IFK Eskilstuna": 1,
		"Halmstads BK": 1,
		"Örebro SK (U)": 2,
		"Tidaholms GIF": 2,
		"Djurgårdens IF": 2,
		"IS Halmia": 2,
		"Kalmar AIK (U)": 3,
		"Surahammars IF": 3,
		"Sandvikens AIK": 3,
		"Örgryte IS (N)": 3,
		"Hammarby IF (N)": 4,
		"Höganäs BK": 4,
		"Karlskoga IF": 4,
		"Hallstahammars SK": 4,
		"Åtvidabergs FF (U)": 5,
		"IFK Kristianstad (U)": 5,
		"Skara IF": 5,
		"Sundbybergs IK (U)": 5,
		"Lundby IF (U)": 6,
		"Finspångs AIK": 6,
		"Ludvika FFI": 6,
		"IFK Malmö": 6,
		"IFK Västerås": 7,
		"Gefle IF": 7,
		"BK Landora": 7,
		"Deje IK": 7,
		"Mjölby AIF": 8,
		"Hofors AIF (U)": 8,
		"Olofströms IF": 8,
		"Billingsfors IK": 8,
		"Värtans IK": 9,
		"Husqvarna IF": 9,
		"IFK Värnamo": 9,
		"Varbergs BoIS": 9,
		"Arvika BK (U)": 10,
		"Malmö BI": 10,
		"Örebro FF (U)": 10,
		"Nynäshamns IF": 10
	},
	{
		"yr": "1939/1940",
		"IFK Norrköping": 1,
		"Reymersholms IK": 1,
		"IS Halmia": 1,
		"Degerfors IF (N)": 1,
		"Surahammars IF": 2,
		"Karlskoga IF": 2,
		"Djurgårdens IF": 2,
		"Malmö BI": 2,
		"Gais": 3,
		"Halmstads BK": 3,
		"Gefle IF": 3,
		"IFK Eskilstuna": 3,
		"IFK Värnamo": 4,
		"Skara IF (U)": 4,
		"Värtans IK": 4,
		"Mjölby AIF": 4,
		"BK Landora": 5,
		"Ludvika FFI": 5,
		"Hallstahammars SK (N)": 5,
		"Varbergs BoIS": 5,
		"Olofströms IF (U)": 6,
		"Skärblacka IF": 6,
		"Nynäshamns IF (U)": 6,
		"Tidaholms GIF": 6,
		"IFK Malmö": 7,
		"Husqvarna IF": 7,
		"Deje IK": 7,
		"Sandvikens AIK (U)": 7,
		"IFK Västerås": 8,
		"Finspångs AIK (U)": 8,
		"Billingsfors IK": 8,
		"Höganäs BK": 8,
		"Ljusne AIK": 9,
		"IFK Trelleborg": 9,
		"Jonsereds IF": 9,
		"IK Tord": 9,
		"Enköpings SK": 10,
		"IF Örnen (U)": 10,
		"Ängelholms IF (U)": 10,
		"IFK Kumla (U)": 10
	},
	{
		"yr": "1938/1939",
		"IFK Göteborg (N)": 1,
		"Halmstads BK": 1,
		"IFK Norrköping": 1,
		"Hammarby IF": 1,
		"IS Halmia": 2,
		"IFK Eskilstuna": 2,
		"Gais (N)": 2,
		"Ludvika FFI (U)": 2,
		"Varbergs BoIS": 3,
		"Skärblacka IF": 3,
		"BK Landora": 3,
		"Djurgårdens IF": 3,
		"Tidaholms GIF": 4,
		"Malmö BI": 4,
		"Ljusne AIK": 4,
		"Surahammars IF": 4,
		"Mjölby AIF": 5,
		"Billingsfors IK": 5,
		"IFK Trelleborg": 5,
		"Reymersholms IK": 5,
		"Karlskoga IF": 6,
		"Husqvarna IF (U)": 6,
		"Värtans IK": 6,
		"IFK Värnamo": 6,
		"IK Tord": 7,
		"IFK Malmö (U)": 7,
		"Gefle IF": 7,
		"Jonsereds IF": 7,
		"Enköpings SK (U)": 8,
		"Höganäs BK": 8,
		"IFK Västerås": 8,
		"Deje IK (U)": 8,
		"Oskarströms IF (U)": 9,
		"Bollnäs GIF": 9,
		"IF Rune (U)": 9,
		"Arvika BK": 9,
		"Motala AIF": 10,
		"Kalmar AIK (U)": 10,
		"Fässbergs IF": 10,
		"IFK Grängesberg": 10
	},
	{
		"yr": "1937/1938",
		"Hammarby IF": 1,
		"Degerfors IF": 1,
		"Malmö BI": 1,
		"Hallstahammars SK": 1,
		"IFK Norrköping (N)": 2,
		"Karlskoga IF": 2,
		"IFK Trelleborg (U)": 2,
		"Djurgårdens IF (N)": 2,
		"Värtans IK": 3,
		"BK Landora": 3,
		"IK Tord": 3,
		"Skärblacka IF": 3,
		"Billingsfors IK": 4,
		"Gefle IF": 4,
		"Höganäs BK": 4,
		"Surahammars IF": 4,
		"Ljusne AIK": 5,
		"Fässbergs IF": 5,
		"Varbergs BoIS (U)": 5,
		"IFK Västerås": 5,
		"Halmstads BK": 6,
		"Mjölby AIF": 6,
		"Reymersholms IK": 6,
		"Arvika BK (U)": 6,
		"Motala AIF (U)": 7,
		"IFK Värnamo (U)": 7,
		"IFK Grängesberg": 7,
		"Tidaholms GIF": 7,
		"IS Halmia": 8,
		"IFK Kumla": 8,
		"Bollnäs GIF": 8,
		"Jonsereds IF": 8,
		"BK Derby": 9,
		"IFK Kristianstad": 9,
		"Alingsås IF": 9,
		"Sundbybergs IK (U)": 9,
		"IFK Hälsingborg": 10,
		"Katrineholms AIK (U)": 10,
		"Karlstads BIK": 10,
		"Skutskärs IF (U)": 10
	},
	{
		"yr": "1936/1937",
		"IK Brage": 1,
		"Degerfors IF": 1,
		"Hammarby IF": 1,
		"Hälsingborgs IF": 1,
		"Halmstads BK (N)": 2,
		"IK Tord (U)": 2,
		"Karlskoga IF": 2,
		"Ljusne AIK": 2,
		"Alingsås IF": 3,
		"Gefle IF": 3,
		"BK Derby": 3,
		"Höganäs BK": 3,
		"Skärblacka IF": 4,
		"Malmö BI": 4,
		"Billingsfors IK": 4,
		"IFK Västerås": 4,
		"BK Landora (U)": 5,
		"Reymersholms IK (U)": 5,
		"Tidaholms GIF (U)": 5,
		"Hallstahammars SK": 5,
		"IFK Kristianstad": 6,
		"IFK Grängesberg (U)": 6,
		"IFK Eskilstuna (N)": 6,
		"Jonsereds IF": 6,
		"Värtans IK": 7,
		"IFK Hälsingborg": 7,
		"Karlstads BIK (U)": 7,
		"Surahammars IF": 7,
		"Bollnäs GIF": 8,
		"Mjölby AIF": 8,
		"Fässbergs IF": 8,
		"IS Halmia": 8,
		"Ängelholms IF": 9,
		"IF Rune (U)": 9,
		"IFK Örebro": 9,
		"Husqvarna IF": 9,
		"IFK Kristinehamn": 10,
		"Växjö BK (U)": 10,
		"Årsta SK": 10,
		"Fagersta AIK": 10
	},
	{
		"yr": "1935/1936",
		"Malmö FF": 1,
		"Billingsfors IK": 1,
		"Hallstahammars SK": 1,
		"Djurgårdens IF": 1,
		"IK Brage": 2,
		"Karlskoga IF": 2,
		"Skärblacka IF (U)": 2,
		"Hälsingborgs IF (N)": 2,
		"Värtans IK (U)": 3,
		"IFK Örebro (U)": 3,
		"Jonsereds IF": 3,
		"IFK Hälsingborg": 3,
		"Husqvarna IF": 4,
		"Gefle IF (N)": 4,
		"Malmö BI": 4,
		"Hammarby IF": 4,
		"Degerfors IF": 5,
		"Höganäs BK": 5,
		"Fagersta AIK (U)": 5,
		"BK Derby": 5,
		"Ängelholms IF": 6,
		"Årsta SK": 6,
		"IFK Kristinehamn (U)": 6,
		"Surahammars IF": 6,
		"Mjölby AIF": 7,
		"Bollnäs GIF": 7,
		"IFK Kristianstad (U)": 7,
		"Fässbergs IF": 7,
		"Ljusne AIK": 8,
		"Alingsås IF (U)": 8,
		"IFK Västerås": 8,
		"IS Halmia": 8,
		"IFK Kumla": 9,
		"IFK Värnamo": 9,
		"IFK Malmö": 9,
		"Sundbybergs IK": 9,
		"Västerviks AIS": 10,
		"Landala IF": 10,
		"Lessebo GIF (U)": 10,
		"Örebro SK": 10
	},
	{
		"yr": "1934/1935",
		"IFK Norrköping": 1,
		"Malmö FF (N)": 1,
		"IK Brage": 1,
		"Gårda BK": 1,
		"IS Halmia (N)": 2,
		"Mjölby AIF": 2,
		"IFK Västerås": 2,
		"Karlskoga IF": 2,
		"Billingsfors IK": 3,
		"IFK Malmö": 3,
		"Hammarby IF": 3,
		"Örebro SK": 3,
		"Djurgårdens IF": 4,
		"Jonsereds IF": 4,
		"IFK Hälsingborg": 4,
		"Hallstahammars SK": 4,
		"Ljusne AIK": 5,
		"BK Derby": 5,
		"Ängelholms IF (U)": 5,
		"Fässbergs IF": 5,
		"Höganäs BK": 6,
		"Surahammars IF": 6,
		"Husqvarna IF": 6,
		"Västerviks AIS (U)": 6,
		"Malmö BI": 7,
		"IFK Kumla": 7,
		"Landala IF (U)": 7,
		"Sundbybergs IK": 7,
		"Årsta SK (U)": 8,
		"Bollnäs GIF (U)": 8,
		"Degerfors IF (U)": 8,
		"IFK Värnamo (U)": 8,
		"IF Rune (U)": 9,
		"Stattena IF": 9,
		"IFK Uddevalla": 9,
		"Åtvidabergs FF": 9,
		"Lunds BK": 10,
		"Kalmar FF": 10,
		"IFK Grängesberg": 10,
		"Slottsbrons IF": 10
	},
	{
		"yr": "1933/1934",
		"IK Sleipner (N)": 1,
		"Landskrona BoIS (N)": 1,
		"Fässbergs IF": 1,
		"IK Brage": 1,
		"Örebro SK (U)": 2,
		"Djurgårdens IF": 2,
		"IFK Hälsingborg (U)": 2,
		"IFK Uddevalla": 2,
		"Gårda BK (U)": 3,
		"IFK Malmö": 3,
		"Surahammars IF": 3,
		"Hammarby IF": 3,
		"Lunds BK": 4,
		"Karlskoga IF": 4,
		"IFK Kumla": 4,
		"IFK Norrköping": 4,
		"Malmö BI": 5,
		"Jonsereds IF": 5,
		"IFK Grängesberg": 5,
		"Sundbybergs IK (U)": 5,
		"Stattena IF": 6,
		"Billingsfors IK": 6,
		"Mjölby AIF": 6,
		"Ljusne AIK (U)": 6,
		"BK Derby": 7,
		"Kalmar FF": 7,
		"Hallstahammars SK": 7,
		"Slottsbrons IF": 7,
		"Åtvidabergs FF": 8,
		"Höganäs BK": 8,
		"Husqvarna IF (U)": 8,
		"IFK Västerås": 8,
		"Motala AIF": 9,
		"Surte IS": 9,
		"IFK Örebro (U)": 9,
		"BK Drott": 9,
		"Krokslätts FF": 10,
		"Reymersholms IK": 10,
		"Lessebo GIF (U)": 10,
		"Brynäs IF": 10
	},
	{
		"yr": "1932/1933",
		"Gefle IF": 1,
		"IFK Norrköping": 1,
		"Krokslätts FF (U)": 1,
		"Halmstads BK": 1,
		"Jonsereds IF (U)": 2,
		"Hammarby IF": 2,
		"BK Drott": 2,
		"IK Brage": 2,
		"Hallstahammars SK (N)": 3,
		"Djurgårdens IF (U)": 3,
		"Billingsfors IK (U)": 3,
		"IFK Malmö (N)": 3,
		"Surahammars IF": 4,
		"Lunds BK (U)": 4,
		"IFK Uddevalla (U)": 4,
		"Åtvidabergs FF (U)": 4,
		"Stattena IF": 5,
		"Fässbergs IF": 5,
		"Mjölby AIF": 5,
		"IFK Kumla": 5,
		"Surte IS (U)": 6,
		"Motala AIF (U)": 6,
		"Kalmar FF (U)": 6,
		"IFK Grängesberg (U)": 6,
		"Brynäs IF (U)": 7,
		"Slottsbrons IF (U)": 7,
		"Malmö BI (U)": 7,
		"Reymersholms IK (U)": 7,
		"IFK Västerås": 8,
		"BK Derby": 8,
		"Karlskoga IF (U)": 8,
		"Höganäs BK": 8,
		"IK City (U)": 9,
		"Sandvikens AIK": 9,
		"Kalmar AIK (U)": 9,
		"Majornas IK (U)": 9,
		"Örebro IK (U)": 10,
		"Degerfors IF (U)": 10,
		"IFK Karlshamn (U)": 10,
		"Westermalms IF": 10
	},
	{
		"yr": "1931/1932",
		"Sandvikens IF (N)": 1,
		"IS Halmia": 1,
		"BK Derby": 2,
		"IFK Norrköping": 2,
		"Halmstads BK": 3,
		"IK Brage": 3,
		"Höganäs BK (U)": 4,
		"IFK Västerås": 4,
		"Stattena IF": 5,
		"Sandvikens AIK": 5,
		"Fässbergs IF": 6,
		"Surahammars IF": 6,
		"Hammarby IF": 7,
		"Mjölby AIF (U)": 7,
		"Gefle IF": 8,
		"BK Drott": 8,
		"Westermalms IF": 9,
		"IFK Kristianstad": 9,
		"IFK Kumla (U)": 10,
		"Skärgårdens IF (U)": 11
	},
	{
		"yr": "1930/1931",
		"Malmö FF": 1,
		"Hallstahammars SK": 1,
		"IK Brage (U)": 2,
		"BK Drott (U)": 2,
		"Fässbergs IF": 3,
		"Hammarby IF": 3,
		"Gefle IF": 4,
		"IFK Kristianstad": 4,
		"IFK Norrköping (N)": 5,
		"Halmstads BK": 5,
		"IS Halmia": 6,
		"Sandvikens AIK": 6,
		"BK Derby": 7,
		"Surahammars IF": 7,
		"Stattena IF (N)": 8,
		"IFK Västerås": 8,
		"Kalmar AIK (U)": 9,
		"Westermalms IF": 9,
		"IK City": 10,
		"Kalmar FF": 10,
		"Mariehofs IF (U)": 11
	},
	{
		"yr": "1929/1930",
		"Redbergslids IK": 1,
		"IFK Eskilstuna (N)": 1,
		"Hammarby IF": 2,
		"Malmö FF": 2,
		"Sandvikens AIK (U)": 3,
		"Fässbergs IF": 3,
		"Halmstads BK": 4,
		"Gefle IF": 4,
		"Hallstahammars SK": 5,
		"BK Derby (U)": 5,
		"IFK Västerås": 6,
		"IFK Kristianstad (U)": 6,
		"Kalmar FF": 7,
		"Westermalms IF (N)": 7,
		"IS Halmia": 8,
		"Surahammars IF": 8,
		"IK City": 9,
		"Krokslätts FF": 9,
		"Köpings IS (U)": 10,
		"IFK Uddevalla": 10,
		"Sundbybergs IK": 11
	},
	{
		"yr": "1928/1929",
		"Stattena IF": 1,
		"Sandvikens IF": 1,
		"Hallstahammars SK": 2,
		"Redbergslids IK": 2,
		"Halmstads BK": 3,
		"Sundbybergs IK": 3,
		"Malmö FF": 4,
		"Hammarby IF": 4,
		"Kalmar FF": 5,
		"Gefle IF": 5,
		"IFK Uddevalla": 6,
		"Surahammars IF": 6,
		"IFK Västerås": 7,
		"Fässbergs IF": 7,
		"IK City": 8,
		"Krokslätts FF": 8,
		"IS Halmia": 9,
		"Djurgårdens IF": 9,
		"IFK Stockholm": 10,
		"Jonsereds IF": 10
	},
	{
		"yr": "1927/1928",
		"Redbergslids IK": 1,
		"Majornas IK": 7,
		"Landskrona IF (U)": 11,
		"Huvudsta IS": 8,
		"Sundbybergs IK": 2,
		"Kalmar FF (U)": 2,
		"Krokslätts FF": 5,
		"Surahammars IF": 4,
		"IF Heimer": 8,
		"BK Derby": 5,
		"IF Vesta (U)": 9,
		"Malmö BI": 8,
		"Varbergs BoIS (U)": 6,
		"IK Sirius": 7,
		"IFK Borås (U)": 11,
		"Söderhamns Skärgårds IF (U)": 4,
		"Westermalms IF (N)": 1,
		"IS Halmia": 5,
		"IK City": 3,
		"IF Linnéa": 7,
		"Köpings IS": 7,
		"Brynäs IF": 6,
		"Sandvikens AIK": 3,
		"IFK Åmål (U)": 12,
		"Skutskärs IF": 9,
		"Hammarby IF": 3,
		"Halmstads BK": 4,
		"Malmö FF": 3,
		"IFK Hälsingborg": 9,
		"Katrineholms": 8,
		"Jonsereds IF": 3,
		"Gefle IF": 2,
		"Västerås IK": 9,
		"Uddevalla IS": 9,
		"IFK Arboga": 10,
		"Hallstahammars SK": 1,
		"Varbergs GIF": 7,
		"IFK Stockholm": 4,
		"Fässbergs IF": 4,
		"IFK Uddevalla (N)": 2,
		"Reymersholms IK": 6,
		"Katrineholms AIK": 6,
		"Skara IF": 6,
		"Trollhättans IF": 10,
		"IFK Malmö": 1,
		"Sandvikens IF": 1,
		"IFK Västerås": 2,
		"IFK Kristianstad (U)": 10,
		"IK Brage": 5,
		"Örebro SK": 5,
		"Kvarnsvedens GIF": 8
	},
	{
		"yr": "1926/1927",
		"Katrineholms AIK": 10,
		"Varbergs GIF": 8,
		"Fässbergs IF": 2,
		"Malmö FF": 6,
		"Jonsereds IF": 5,
		"Västerås IK": 3,
		"Huvudsta IS": 6,
		"Skara IF": 1,
		"Sandvikens IF": 1,
		"Lunds BK": 10,
		"BK Derby": 2,
		"Hallstahammars SK": 4,
		"Sundbybergs IK": 4,
		"Brynäs IF": 4,
		"Djurgårdens IF": 1,
		"IFK Stockholm": 5,
		"Stattena IF": 1,
		"IS Halmia": 2,
		"Surahammars IF": 7,
		"Krokslätts FF": 4,
		"IFK Malmö": 5,
		"Hammarby IF": 3,
		"Kvarnsvedens GIF": 6,
		"Ängelholms IF": 9,
		"IFK Västerås": 2,
		"IK Sirius": 8,
		"IFK Hälsingborg": 7,
		"Västerås SK": 11,
		"Kolbäcks AIF": 12,
		"Majornas IK": 3,
		"IFK Arboga": 9,
		"Trollhättans IF": 8,
		"Reymersholms IK": 8,
		"Halmstads BK": 3,
		"Skutskärs IF": 7,
		"Vänersborgs IF": 9,
		"Sandvikens AIK": 2,
		"IF Heimer": 7,
		"Stockholms BK": 10,
		"Gefle IF": 5,
		"Köpings IS": 5,
		"Katrineholms SK": 8,
		"Malmö BI": 4,
		"IK Brage": 3,
		"IK Ymer": 10,
		"IK City": 1,
		"Uddevalla IS": 6,
		"Mariebergs IK": 9,
		"Örebro SK": 6,
		"IF Linnéa": 7
	},
	{
		"yr": "1925/1926",
		"Sundbybergs IK": 2,
		"Västerås SK": 6,
		"Västerås IK": 3,
		"IS Halmia": 6,
		"Jonsereds IF": 3,
		"Varbergs GIF": 8,
		"Brynäs IF": 3,
		"IK Sirius": 10,
		"Fässbergs IF": 4,
		"Reymersholms IK": 7,
		"Sandvikens AIK": 5,
		"IFK Hälsingborg": 5,
		"IFK Stockholm": 5,
		"Gefle IF": 2,
		"Sandvikens IF": 1,
		"Djurgårdens IF": 3,
		"Katrineholms SK": 8,
		"Mariebergs IK": 8,
		"Halmstads BK": 1,
		"Örebro SK": 1,
		"IF Elfsborg": 1,
		"Stattena IF": 2,
		"Köpings IS": 5,
		"Krokslätts FF": 5,
		"Lunds BK": 7,
		"Skara IF": 6,
		"Falkenbergs GIK": 9,
		"Kvarnsvedens IF": 6,
		"Örebro IK": 9,
		"Stockholms BK": 9,
		"IF Heimer": 9,
		"Hallstahammars SK": 2,
		"Malmö BIF": 4,
		"Uddevalla IS": 8,
		"Katrineholms AIK": 7,
		"IF Linnéa": 4,
		"Hammarby IF": 6,
		"Domnarvets GIF": 7,
		"Falu IF": 8,
		"IFK Örebro": 10,
		"IFK Västerås": 4,
		"Malmö FF": 3,
		"Vänersborgs IF": 2,
		"Trollhättans IF": 7,
		"Westermalms IF": 1,
		"Tranebergs IF": 11,
		"Skutskärs IF": 4
	}
]
